# Generated by Django 5.0.2 on 2024-02-28 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GiftVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_code', models.CharField(max_length=100, unique=True)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('usage_date', models.DateField(blank=True, null=True)),
                ('source_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vales_origem', to='app_control.store')),
                ('store_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vales_utilizados', to='app_control.store')),
            ],
        ),
    ]
