# Generated by Django 5.0.2 on 2024-02-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftvoucher',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
