# Generated by Django 5.0.2 on 2024-03-12 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0004_remove_giftvoucher_status_bar_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='GiftVoucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_bar_code', to='app_control.giftvoucher'),
        ),
    ]
