# Generated by Django 5.0.2 on 2024-03-12 17:24

import app_control.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0005_alter_barcode_giftvoucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='bar_code',
            field=models.CharField(max_length=13, validators=[app_control.models.validate_length]),
        ),
    ]
