# Generated by Django 5.0.2 on 2024-03-14 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0006_alter_barcode_bar_code'),
        ('user_control', '0002_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftvoucher',
            name='source_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vales_origem', to='user_control.store'),
        ),
        migrations.AlterField(
            model_name='giftvoucher',
            name='store_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vales_utilizados', to='user_control.store'),
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
