# Generated by Django 5.0.2 on 2024-03-14 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0007_alter_giftvoucher_source_store_and_more'),
        ('user_control', '0003_remove_store_created_by_customuser_user_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftvoucher',
            name='store_used',
        ),
        migrations.AddField(
            model_name='barcode',
            name='store_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vales_utilizados', to='user_control.store'),
        ),
    ]
