# Generated by Django 5.0.2 on 2024-03-14 17:02

import app_control.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0008_remove_giftvoucher_store_used_barcode_store_used'),
        ('user_control', '0003_remove_store_created_by_customuser_user_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftvoucher',
            name='bar_code',
            field=models.CharField(max_length=13, null=True, validators=[app_control.models.validate_length]),
        ),
        migrations.AddField(
            model_name='giftvoucher',
            name='status_bar_code',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='giftvoucher',
            name='store_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vales_utilizados', to='user_control.store'),
        ),
        migrations.DeleteModel(
            name='BarCode',
        ),
    ]
