# Generated by Django 5.0.2 on 2024-03-19 10:47

import app_control.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0009_giftvoucher_bar_code_giftvoucher_status_bar_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftvoucher',
            name='bar_code',
            field=models.CharField(max_length=13, null=True, unique=True, validators=[app_control.models.validate_length]),
        ),
    ]
